### PR TITLE
Parse coursework dates into one column

### LINKED ISSUE #39: Add dueDate parsing to CourseWork
Currently the dueDate timestamp is parsed into the following fields:

- dueDate.year
- dueDate.month
- dueDate.day
- duetTime.hours
- dueTime.minutes

It would be preferable for this to be a single datetime field.

### PR DESCRIPTION
**Pull request by zkagin**
Depends on #43 
Fixes #39, #40 

Parses the separate coursework dueDate and dueTime columns into a single date column. This should fix a bug where having no dueDate in the first batch of coursework led to a column with an incorrect data type.

### CODE REVIEW

**Comment by dchess** [comment]
@zkagin This is ready to merge. Can you rebase?

**Comment by zkagin** [comment]
@dchess Rebase done.

**Comment by zkagin** [comment]
@dchess Whoops, I rebased but didn't change the branch it was off of. We will need to back this out and re-merge into master instead.

**Comment by zkagin** [comment]
@dchess I just created a new PR with this again, this time merging into master.

https://github.com/kipp-bayarea/google_classroom/pull/53/commits

**Pull request merged**
